apps/dashboard/urls.py
from django.conf.urls import url
from . import views
app_name='dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.add_user, name='add_user'),
    url(r'^create$', views.create_user, name='create_user'),
    url(r'^edit/(?P<user_id>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^update/(?P<user_id>\d+)/$', views.update_user, name='update_user'),
    url(r'^update/(?P<user_id>\d+)/description$', views.update_user_description, name='update_user_description'),
    url(r'^destroy_user/(?P<user_id>\d+)$', views.destroy_user, name='destroy_user'),
    url(r'^show/(?P<user_id>\d+)$', views.show_user, name='show_user'),
    url(r'^create_message/(?P<wall_id>\d+)$', views.create_message, name='create_message'),
    url(r'^create_comment/(?P<message_id>\d+)$', views.create_comment, name='create_comment'),
]

apps/harttv_app/urls.py
from django.conf.urls import url
from . import views
app_name='harttv'
urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^show/(?P<show_maze_id>\d+)$', views.view_show, name='view_show'),
    url(r'^show/search$', views.test_search_bar, name='test_search_bar'),
    url(r'^show/search/results$', views.search_results, name='search_results'),
    url(r'^show/all$', views.view_all_shows, name='view_all_shows'),
    url(r'^show/top$', views.top_rated_shows, name='top_rated_shows'),
    url(r'^show/(?P<show_id>\d+)/handle_add_review$', views.handle_add_review, name='handle_add_review'),
    url(r'^show/(?P<review_id>\d+)/(?P<show_id>\d+)/handle_delete_review$', views.handle_delete_review, name='handle_delete_review'),

    url(r'^show/(?P<show_id>\d+)/handle_add_favorite$', views.handle_add_favorite, name='handle_add_favorite'),
    url(r'^show/(?P<show_id>\d+)/handle_remove_favorite$', views.handle_remove_favorite, name='handle_remove_favorite'),
    url(r'^episode/(?P<episode_id>\d+)$', views.view_episode, name='view_episode'),
    url(r'^episode/(?P<episode_id>\d+)/handle_add_episode_comment$', views.handle_add_episode_comment, name='handle_add_episode_comment'),
    url(r'^episode/(?P<episode_id>\d+)/(?P<comment_id>\d+)handle_delete_episode_comment$', views.handle_delete_episode_comment, name='handle_delete_episode_comment'),
    url(r'^episode/(?P<episode_id>\d+)/handle_update_episode_rating$', views.handle_update_episode_rating, name='handle_update_episode_rating'),
    url(r'^about$', views.about, name='about'),

]

harttv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.harttv_app.urls', namespace='harttv')),
    url(r'^', include('apps.login_registration.urls', namespace='auth')),
    url(r'^users/', include('apps.dashboard.urls', namespace='dashboard')),
]

apps/dashboard/models.py
from __future__ import unicode_literals
from ..login_registration.models import User
from django.db import models

# Create your models here.
class Message(models.Model):
    message_text = models.TextField()
    wall = models.ForeignKey(User, related_name="wall_messages")
    user = models.ForeignKey(User, related_name="users_messages")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    comment_text = models.TextField()
    message = models.ForeignKey(Message, related_name='messages_comments')
    commenter = models.ForeignKey(User, related_name='users_comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Description(models.Model):
    description_text = models.TextField(max_length=1024)
    user = models.OneToOneField(User, on_delete=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/dashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
from ..login_registration.models import User
from .models import Message, Comment, Description
from ..harttv_app.models import Show, ShowRating, Review
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
import bcrypt
from django.http import HttpResponseRedirect


# Create your views here.
def index(request):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    user = User.objects.get(id=request.session['id'])
    boolean = user.admin
    context = {
        "users": User.objects.all(),
        "boolean": boolean
    }

    return render(request, 'dashboard/dashboard.html', context)



def add_user(request):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    user = User.objects.get(id=request.session['id'])
    boolean = user.admin
    if boolean:
        return render(request, 'dashboard/add_user.html')
    else:
        return redirect('dashboard:index')


def create_user(request):
    if request.method =='POST':
        userObject = User.objects.isValidRegistration(request.POST)
    return redirect(reverse('dashboard:index'))

def edit_user(request, user_id):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    print user_id
    user = User.objects.get(id=user_id)

        

    admin_user = User.objects.get(id=request.session['id'])
    context = {
        "user": user,
        "boolean": admin_user.admin,
    }

    description = Description.objects.filter(user=user)
    if len(description) > 0:
        context['description'] = description[0]
    if admin_user.admin or int(user_id) == request.session['id']:
        print user.admin
        print "i'm an admin"
        return render(request, 'dashboard/edit_user.html', context)
    else:
        print "not rendering correctly >:("
        return redirect(reverse('dashboard:index'))

def update_user(request, user_id):
    user = User.objects.get(id=user_id)
    if request.method == "POST":
        print request.POST
        if 'password' in request.POST and request.POST['password'] == request.POST['password']:
            hashed = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
            print hashed
            user.password = hashed
            user.save()
            #user.password = request.POST['password']
        else:
            user.email = request.POST['email']
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            if 'admin' in request.POST:
                user.admin = request.POST['admin']
            user.save()

    # if password in request.POST
    # do password change
    #else do information change.
    return redirect(reverse('dashboard:index'))

def update_user_description(request, user_id):
    user = User.objects.get(id=user_id)
    description = Description.objects.filter(user=user)
    if request.method == 'POST':
        if len(description) > 0:
            Description.objects.filter(user=user).update(description_text=request.POST['description'])
        else:
            Description.objects.create(description_text=request.POST['description'], user=user)
    return redirect(reverse('dashboard:index'))
    
        
    
    

def destroy_user(request, user_id):
    current_user = User.objects.get(id=request.session['id'])
    user_to_delete = User.objects.get(id=user_id)
    if current_user.admin and not user_to_delete.admin:
        user = User.objects.get(id=user_id).delete()
    return redirect(reverse('dashboard:index'))

def show_user(request, user_id):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    user = User.objects.get(id=user_id)
    if Description.objects.filter(user=user):
        description = Description.objects.get(user=user)
    else:
        description = "The user has not yet entered a bio!"
    context = {
        "user": user,
        "messages": Message.objects.filter(wall=user),
        "top_rated_shows": ShowRating.objects.filter(user=user).order_by('-rating', 'show__title'),
        "users_reviews": Review.objects.filter(user=user).order_by('-rating__rating'),
        "description": description,
    }
    #create forms, render messages on show page and you're done :)
    return render(request, 'dashboard/show_user.html', context)

def create_message(request, wall_id):
    if request.method == 'POST':
        wall_id = wall_id
        poster_id = request.session['id']
        user_who_owns_wall = User.objects.get(id=wall_id)
        user_who_posted_message = User.objects.get(id=poster_id)

        Message.objects.create(message_text=request.POST['message'], wall=user_who_owns_wall, user=user_who_posted_message)

        print "the wall and poster ids are", wall_id, poster_id
        url = reverse('dashboard:show_user', kwargs={'user_id': wall_id})
        return HttpResponseRedirect(url)
    
def create_comment(request, message_id):
    if request.method =='POST':
        message_id = message_id
        message = Message.objects.get(id=message_id)
        user_who_commented = User.objects.get(id=request.session['id'])
        wall_id = message.wall.id

        Comment.objects.create(comment_text=request.POST['comment'], message=message, commenter=user_who_commented)
        url = reverse('dashboard:show_user', kwargs={'user_id': wall_id})
        return HttpResponseRedirect(url)

apps/dashboard/templates/dashboard/add_user.html
{% extends 'harttv_app/base.html' %}
    {% block content %}
            <h1>Hello New User!</h1>
            
            <form action="{% url 'dashboard:create_user' %}" method='post'>
                {% csrf_token %}
                <div class="form-group">
                    <label for='first_name'>First Name: </label>
                    <input type='text' name='first_name' id='first_name' class='form-control' placeholder="First name">
                </div>
                <div class="form-group">
                    <label for='last_name'>Last Name: </label>
                    <input type='text' name='last_name' id='last_name' class='form-control' placeholder="Last name">
                </div>

                <div class="form-group">
                    <label for='email'>Email: </label>
                    <input type='text' name='email' id='email' class='form-control' placeholder="Email">
                </div>

                <div class="form-group">
                    <label for='password'>Password: </label>
                    <input type='password' name='password' id='password' class='form-control' placeholder="Password">
                </div>

                <div class="form-group">
                    <label for='confirm_password'>Confirm Password: </label>
                    <input type='password' name='confirm_password' id='confirm_password' class='form-control' placeholder="Confirm Password">
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>
    {% endblock %}

apps/dashboard/templates/dashboard/dashboard.html
{% extends 'harttv_app/base.html' %}
    {% block content %}
            <h1>Hello {{request.session.first_name}}, Here's the 
                {% if boolean %}
                Admin
                {% else %}
                User
                {% endif %}
                Dashboard!</h1>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Join Date</th>
                        <th>User Level</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{user.id}}</td>
                        <td><a href="{% url 'dashboard:show_user' user_id=user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
                        <td>{{user.created_at|date:"m/d/Y"}}</td>
                        {% if user.admin == True %}
                            <td>Admin</td>
                        {% else %}
                            <td>Normal</td>
                        {% endif %}
                        <td>
                            {% if boolean or user.id == request.session.id %}
                            <a href="{% url 'dashboard:edit_user' user_id=user.id %}">Edit</a>
                            {% else %}
                            No Permissions
                            {% endif %}
                            {% if boolean and not user.admin %}
                            <a href="{% url 'dashboard:destroy_user' user_id=user.id %}">Delete</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if boolean %}
            <a href="{% url 'dashboard:add_user' %}" type="submit" class="btn btn-default">Add a new user!</a>
            {% endif %}
    {% endblock %}

apps/dashboard/templates/dashboard/edit_user.html
{% extends 'harttv_app/base.html' %}
    {% block content %}
            <p class='edit-profile-title' id='edit-profile'>{{user.first_name}} {{user.last_name}}</p><p class='edit-profile-title' id='edit-profile-name'>&nbsp;//&nbsp;Edit Profile</h4>
            <div class='row'>
            <div class='col-md-4'>
                <h3 class='edit-header'>Update Information</h3>
                <form action="{% url 'dashboard:update_user' user_id=user.id %}" method='post'>
                    {% csrf_token %}
                    <div class='form-group'>
                        <label for='email'>Email: </label>
                        <input type='text' name='email' id='email' class='form-control' value="{{user.email}}">
                    </div>
                    <div class='form-group'>
                        <label for='first_name'>First Name: </label>
                        <input type='text' name='first_name' id='first_name' class='form-control' value="{{user.first_name}}">
                    </div>
                    <div class="form-group">
                        <label for='last_name'>Last Name: </label>
                        <input type='text' name='last_name' id='last_name' class='form-control' value="{{user.last_name}}">
                    </div>

                    {% if boolean %}
                    <label for='admin'>Admin: </label>
                    <div class="form-group">
                        <select name='admin' class='form-control' style='max-width: 60%'>
                            <option value='False'>Normal</option>
                            <option value='True' selected>Admin</option>
                        </select>
                    </div>
                    {% endif %}
                    
                    <button type="submit" class="btn btn-default submit-button">Submit</button>
                </form>

            </div>
            <div class='col-md-4'>
                <h3 class='edit-header'>Change Password</h3>
                <form action="{% url 'dashboard:update_user' user.id %}" method='post'>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for='password'>Password: </label>
                        <input type='password' name='password' id='password' class='form-control' placeholder="Password">
                    </div>

                    <div class="form-group">
                        <label for='confirm_password'>Confirm Password: </label>
                        <input type='password' name='confirm_password' id='confirm_password' class='form-control' placeholder="Confirm Password">
                    </div>
                    <button type="submit" class="btn btn-default submit-button">Submit</button>
                </form>
            </div>
            </div>

            <div class='row'>
            <div class='col-md-4'>
                <h3 class='edit-header'>Update Description</h3>
                <form action="{% url 'dashboard:update_user_description' user.id %}" method='post'>
                    {% csrf_token %}
                    <div class='form-group'>
                        <textarea style="max-width: 100%;" name='description' class='form-control'>{{description.description_text}}</textarea>
                        <button type="submit" class="btn btn-default submit-button update-description-button">Update</button>  
                    </div>
                </form>
            </div>
            </div>

    {% endblock %}
            
            

apps/dashboard/templates/dashboard/show_user.html
{% extends 'harttv_app/base.html' %}
    {% block content %}
            <div class='col-md-12' style="margin-bottom: 100px;">
                <div class='row'>
                <p class='edit-profile-title' id='edit-profile'>{{user.first_name}} {{user.last_name}}</p><p class='edit-profile-title' id='edit-profile-name'>&nbsp;//&nbsp;View Profile</p>
                </div>
                <div class='row'>
                    <div class='col-md-6'>
                        <p class='show-table-description'>{{description.description_text}}</p>
                        <p class='show-table-description'>Joined: {{user.created_at|date:"F Y"}} </h4>
                    </div>
                </div>
                <div class='row'>
                    <div class='col-md-4'>
                        <h3 class='edit-profile-title'>Favorite Shows</h3>
                        <div class='favorite-shows'>
                        
                            {% for favorite in user.users_favorites.all %}
                                <div class="col-sm-4" class='individual-episode-container'>
                                    <a href="{% url 'harttv:view_show' favorite.maze_id %}"><img src="{{favorite.image_link}}" class='favorite-image' alt="Ep Thumbnail" style="max-width: 100%; max-height: 100%;"></a>
                                </div>
                                {% if forloop.counter|divisibleby:3 %}
   

                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <div class='col-md-4'>
                        <h3 class='edit-profile-title'>Top Rated Shows</h3>
                        <div class='favorite-shows'>
                            {% for rated_show in top_rated_shows %}

                                <div class="col-sm-4" class='individual-episode-container'>
                                    <a href="{% url 'harttv:view_show' rated_show.show.maze_id %}"><img src="{{rated_show.show.image_link}}" class='favorite-image' alt="Ep Thumbnail" style="max-width: 100%; max-height: 100%;"></a>
                                </div>
                                {% if forloop.counter|divisibleby:3 %}

                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <div class='col-md-4'>
                        <h3 class='edit-profile-title'>User's Reviews</h3>
                        <div class='favorite-shows'>
                            {% for review in users_reviews %}
                                <p class='user-page-review-title'><a href="{% url 'harttv:view_show' review.show.maze_id %}"><span class='top-rated-show-title'>{{review.title}}</span>&nbsp;//&nbsp;<span class='top-rated-show-title' style="font-size:1em;">{{review.show.title}}</span></a></p>
                                <p class='user-page-review-rating'>Score: {{review.rating.rating}}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>


                
                <div class='col-md-12' style='max-width: 60%; margin-top: 20px;'>
                    <div class='row'>
                        <p class='edit-profile-title' id='edit-profile'>{{user.first_name}}'s Wall</p>
                    </div>
                        {% for message in messages %}
                            <div class='message_container'>
                                <div class='row'>
                                    <div class='initial-message'>
                                        <p class='message-author'>{{message.user.first_name}} {{message.user.last_name}} - <span class='message-date'>{{message.created_at|timesince}} ago</span></p>
                                        <p class='message-text'>{{message.message_text}}</p>
                                    </div>
                                </div>
                                {% for comment in message.messages_comments.all %}
                                    <div class='comment_container'>
                                        <p class='comment-author'>{{comment.commenter.first_name}} {{comment.commenter.last_name}} - <span class='comment-date'>{{comment.created_at|timesince}} ago</span></p>
                                        <p>{{comment.comment_text}}</p>
                                    </div>
                                {% endfor %}
                            

                            <form action="{% url 'dashboard:create_comment' message.id %}" method='post'>
                                {% csrf_token %}
                                <div class='form-group' style='margin-left: 10px;'>
                                    <label for="comment">Leave a comment on this message</label>
                                    <textarea name='comment' id='comment' class='form-control' style='max-width: 64%;'></textarea>
                                    <button type="submit" class="btn btn-default message-comment-submit">Comment!</button>
                                </div>
                            </form>

                        {% endfor %}
                
                    
                    <div class='row'>
                        <form action="{% url 'dashboard:create_message' user.id %}" method='post'>
                            {% csrf_token %}
                            <div class='form-group'>
                                <label for="message">Leave a Message for {{user.first_name}}</label>
                                <textarea name='message' id='message' class='form-control'></textarea>
                                <button type="submit" class="btn btn-default message-comment-submit">Submit</button>
                            </div>
                        </form>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        {% endblock %}