apps/dashboard/urls.py
from django.conf.urls import url
from . import views
app_name='dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.add_user, name='add_user'),
    url(r'^create$', views.create_user, name='create_user'),
    url(r'^edit/(?P<user_id>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^update/(?P<user_id>\d+)/$', views.update_user, name='update_user'),
    url(r'^update/(?P<user_id>\d+)/description$', views.update_user_description, name='update_user_description'),
    url(r'^destroy_user/(?P<user_id>\d+)$', views.destroy_user, name='destroy_user'),
    url(r'^show/(?P<user_id>\d+)$', views.show_user, name='show_user'),
    url(r'^create_message/(?P<wall_id>\d+)$', views.create_message, name='create_message'),
    url(r'^create_comment/(?P<message_id>\d+)$', views.create_comment, name='create_comment'),
]

apps/harttv_app/urls.py
from django.conf.urls import url
from . import views
app_name='harttv'
urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^show/(?P<show_maze_id>\d+)$', views.view_show, name='view_show'),
    url(r'^show/search$', views.test_search_bar, name='test_search_bar'),
    url(r'^show/search/results$', views.search_results, name='search_results'),
    url(r'^show/all$', views.view_all_shows, name='view_all_shows'),
    url(r'^show/top$', views.top_rated_shows, name='top_rated_shows'),
    url(r'^show/(?P<show_id>\d+)/handle_add_review$', views.handle_add_review, name='handle_add_review'),
    url(r'^show/(?P<review_id>\d+)/(?P<show_id>\d+)/handle_delete_review$', views.handle_delete_review, name='handle_delete_review'),

    url(r'^show/(?P<show_id>\d+)/handle_add_favorite$', views.handle_add_favorite, name='handle_add_favorite'),
    url(r'^show/(?P<show_id>\d+)/handle_remove_favorite$', views.handle_remove_favorite, name='handle_remove_favorite'),
    url(r'^episode/(?P<episode_id>\d+)$', views.view_episode, name='view_episode'),
    url(r'^episode/(?P<episode_id>\d+)/handle_add_episode_comment$', views.handle_add_episode_comment, name='handle_add_episode_comment'),
    url(r'^episode/(?P<episode_id>\d+)/(?P<comment_id>\d+)handle_delete_episode_comment$', views.handle_delete_episode_comment, name='handle_delete_episode_comment'),
    url(r'^episode/(?P<episode_id>\d+)/handle_update_episode_rating$', views.handle_update_episode_rating, name='handle_update_episode_rating'),
    url(r'^about$', views.about, name='about'),

]

apps/login_registration/urls.py
from django.conf.urls import url
from . import views

app_name='auth'
urlpatterns =[
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    ]

harttv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.harttv_app.urls', namespace='harttv')),
    url(r'^', include('apps.login_registration.urls', namespace='auth')),
    url(r'^users/', include('apps.dashboard.urls', namespace='dashboard')),
]

apps/harttv_app/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from django.contrib import messages
from django.db.models import Count, Avg
from .models import Show, Episode, Review, EpisodeComment, EpisodeRating, ShowRating, RecentlyViewedShow
import datetime
import pytvmaze
import threading
import random

from ..login_registration.models import User
tvm = pytvmaze.TVMaze('mtjhartley')
# Create your views here.


# def is_user_logged_in(request):
#     if not 'id' in request.session:
#         return redirect(reverse('auth:index'))

def generate_rating_options():
    ratings = [1,2,3,4,5,6,7,8,9,10]
    ratings_strings = ["(1) Appalling", "(2) Atrocious", "(3) Very Bad", "(4) No Good", "(5) Alright", "(6) Good", "(7) Enjoyable", "(8) Great", "(9) Amazing", "(10) Swag Me Out!"]
    rating_options = zip(ratings, ratings_strings)
    return rating_options

def get_users_recently_viewed_shows(user):
    last_4_viewed = []

    users_recently_viewed = list(RecentlyViewedShow.objects.filter(user=user).order_by('-created_at').values_list('show__title', 'show__maze_id', 'show__image_link').distinct())
    
    iter_index = 0
    while len(last_4_viewed) < 4 and iter_index < len(users_recently_viewed):
        if users_recently_viewed[iter_index] not in last_4_viewed:
            last_4_viewed.append(users_recently_viewed[iter_index])
        iter_index += 1
    return last_4_viewed


#@login_required(login_url='auth:index')
def index(request):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    user = User.objects.get(id=request.session['id'])
    recently_viewed_shows = get_users_recently_viewed_shows(user)

    random_idx = random.randint(0, Show.objects.count() - 1)
    random_show = Show.objects.all()[random_idx]
    # show_average_rating = ShowRating.objects.aggregate(Avg('rating')).order_by('-rating').distinct('show')
    #try with recenetly viewed shows

    # all_shows_average_rating = Show.objects.values_list('title').annotate(Avg('show_ratings'))
    # print all_shows_average_rating
    context = {
        "show": random_show,
        "recently_viewed": recently_viewed_shows,

    }
    return render(request, 'harttv_app/index.html', context)

def top_rated_shows(request):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    top_ranked_shows = ShowRating.objects.values_list('show__title', 'show__maze_id', 'show__image_link', 'show__premiered', 'show__network', 'show__description').annotate(average_rank=Avg('rating')).order_by('-average_rank')[:10]
    print top_ranked_shows
    context = {
        "shows": top_ranked_shows,
    }
    print top_ranked_shows[0]
    print top_ranked_shows[0][0]
    print top_ranked_shows[0][1]
    print top_ranked_shows[0][2]
    print top_ranked_shows
    return render(request, 'harttv_app/top_rated_shows.html', context)

def view_all_shows(request):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    context = {
        "shows": Show.objects.all().order_by('title')
    }
    return render(request, 'harttv_app/all_shows.html', context)




    

def view_show(request, show_maze_id):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    user = User.objects.get(id=request.session['id'])
    if len(Show.objects.filter(maze_id=show_maze_id)) == 1:
        show = Show.objects.get(maze_id=show_maze_id)
        print "show is already in the database"
    else: #show is NOT in the database
        show = Show.objects.createShow(maze_id=show_maze_id)
        print "show is not in the database"
        #threading code to add episodes to db if first time visiting page
        iterate_show = tvm.get_show(maze_id=show.maze_id, embed='episodes')
        print iterate_show.name
        print iterate_show.summary
        for episode in iterate_show.episodes:
            print "threading"
            thread = threading.Thread(target=Episode.objects.createEpisode, args=(show.id, episode))
            thread.start()
            thread.join()
            print "threading complete"
        #thread.wait loop
    print "*" * 50
    print "testing seasons and episodes"
    print User.get_rating(user, show.id)
    #adding to recently viewed
    RecentlyViewedShow.objects.create(user=user, show=show)
    
    #if show is in users favorites, context favorited : True
    #else context favorited: False
    print show.favorite.filter(id=user.id)

    #refactor toShowReview nad ShowRating
    if len(ShowRating.objects.filter(show=show, user=user)) > 0:
        rating = ShowRating.objects.get(show=show, user=user).rating
    else:
        rating = None
    
    favorited = len(show.favorite.filter(id=user.id)) > 0 
    #return true or false if favorited
    print favorited
    show_average_rating = ShowRating.objects.filter(show=show).aggregate(Avg('rating'))
    show_num_users_rated = len(ShowRating.objects.filter(show=show))
    print 'printing average_rating'
    print show_average_rating
    print 
    print "how many users have favorited this show: "
    print show.favorite.all().count()
    ratings_options = generate_rating_options()
    episodes = Episode.objects.filter(show__maze_id=show.maze_id).annotate(number_eps=Count('show__episodes')).order_by('season_number', 'episode_number')
    context = {
        "show": show,
        "episodes": episodes,
        "recent_episodes": episodes[:6],
        "num_episodes": len(episodes), #can probably do with...Episode.objects.filter(show__episodes.)
        "favorited": favorited,
        "options": ratings_options,
        "current_rating": rating,
        "show_average_rating": show_average_rating['rating__avg'],
        "show_num_users_rated": show_num_users_rated,
        "favorites": show.favorite.all().count(),
    }
    

    # code to add episodes to the database if the show doesn't exist. 
    # iterate_show = tvm.get_show(maze_id=show.maze_id, embed='episodes')
    # print iterate_show.name
    # print iterate_show.summary
    # for episode in iterate_show.episodes:
    #     print "threading"
    #     thread = threading.Thread(target=Episode.objects.createEpisode, args=(show.id, episode))
    #     thread.start()
    #     print "threading complete"

    
    return render(request, 'harttv_app/view_show.html', context)


def test_search_bar(request):
    return render(request, 'harttv_app/search.html')        

def search_results(request):
    if not 'id' in request.session:
        return redirect(reverse('auth:index'))
    search = request.GET['show_search']
    search_string = search.strip().lower() #check if tvmaze is case sensitive
    print "*" * 50
    print search_string
    try:
        searchShows = pytvmaze.get_show_list(search_string)
        results = True

    except:
        searchShows = []
        results = False
    print "shows"
    print searchShows
    print "type(shows)"
    print type(searchShows)
    # print type(searchShows[0])
    print "name and id"
    # print "name", searchShows[0].name
    # print "id", searchShows[0].maze_id
    print "for loop"
    show_list = []
    #for some reason, can't just pass in the searchShows to context...
    for show in searchShows:
        showDict = {}
        showDict['name'] = show.name
        showDict['maze_id'] = show.maze_id
        if show.summary:
            summary_array = show.summary.split(" ")
            showDict['description'] = ' '.join([x for x in summary_array[:100]]) + '...'
        if show.premiered:
            print show.premiered
            showDict['airdate'] = datetime.datetime.strptime(show.premiered, '%Y-%m-%d').date()
        else:
            showDict['airdate'] = 'N/A'
        if show.network:
            showDict['network'] = show.network.name
        else:
            showDict['network'] = 'N/A'
        if show.image:
            showDict['image'] = show.image['original']
        show_list.append(showDict)


    context = {
        #"searchShows": searchShows,
        "contextShow": show_list,
        "search": search,
        "results": results,
    }
    return render (request, 'harttv_app/search_results.html', context)

def handle_add_review(request, show_id):
    
    if request.method == 'POST':
        show = Show.objects.get(id=show_id)
        user = User.objects.get(id=request.session['id'])
        print show
        print user
        review_title = request.POST['title']
        review_text = request.POST['review']  
        existing_rating = ShowRating.objects.filter(user=user, show=show)
        if len(review_title) == 0 and len(review_text) == 0:
            if existing_rating:
                existing_rating[0].rating = int(request.POST['rating'])
                existing_rating[0].save()
                rating = existing_rating[0]
            else:
                rating = ShowRating.objects.create(user=user, show=show, rating=int(request.POST['rating']))
            url = reverse('harttv:view_show', kwargs={'show_maze_id': show.maze_id})
            return HttpResponseRedirect(url)
        else:
            if existing_rating:
                existing_rating[0].rating = int(request.POST['rating'])
                existing_rating[0].save()
                rating = existing_rating[0]
            else:
                rating = ShowRating.objects.create(user=user, show=show, rating=int(request.POST['rating']))
            Review.objects.create(title=review_title, text=review_text,user=user, show=show, rating=rating)
            url = reverse('harttv:view_show', kwargs={'show_maze_id': show.maze_id})
            return HttpResponseRedirect(url)

def handle_delete_review(request, review_id, show_id):
    if request.method == 'POST':
        Review.objects.get(id=review_id).delete()
        show = Show.objects.get(id=show_id)
        url = reverse('harttv:view_show', kwargs={'show_maze_id': show.maze_id})
        return HttpResponseRedirect(url)

apps/harttv_app/templates/harttv_app/about.html
{% extends 'harttv_app/base.html' %}
{% block content %}
    <!--new header ends here -->

        <h1>About Page</h1>

{% endblock %}

        

apps/harttv_app/templates/harttv_app/all_shows.html
{% extends 'harttv_app/base.html' %}
{% block content %}


    {% for show in shows %}
    <div class='row show-row'>
        <div class='col-md-12 show-table-header'>
            <div class='row'>
                <div class='col-md-2'>
                    <p class='show-table-title'><a href="{% url 'harttv:view_show' show_maze_id=show.maze_id %}">{{show.title}}</a></h3>
                </div>
                <div class='col-md-10'>
                    <div class='stats-holder'><p class='show-table-stats'> Network: {% if not show.network %} N/A {% else %} {{show.network}} {% endif %}</p></div>
                    <div class='stats-holder'><p class='show-table-stats'>Premiered: {{show.premiered|date:"Y"}}</p></div>
                    <div class='stats-holder'><p class='show-table-stats'>ID #{{show.maze_id}}</p></div>
                </div>
            </div>
            <div class='row'>
                <div class='col-md-2'>
                    <a href="{% url 'harttv:view_show' show_maze_id=show.maze_id %}"><img class='all-show-image' src="{{show.image_link}}"></a>
                </div>
                <div class='col-md-10'>
                    <p class='show-table-description'>{{show.description|truncatewords:200}}</p>
                </div>
            </div>
        </div>

    </div>
    {% endfor %}

{% endblock %}

apps/harttv_app/templates/harttv_app/base.html
{% url 'harttv:about' as harttvabout %}
{% url 'harttv:view_all_shows' as harttvview_all_shows %}
{% url 'harttv:index' as harttvindex %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        {% load staticfiles %}
        <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:400,900" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'harttv_app/css/style.css' %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'harttv:index' %}">Hart<span class='hart_tv_TV'>TV</span></a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% ifequal request.path harttvindex %}active{% endifequal %}"><a href="{% url 'harttv:index' %}">Home <span class="sr-only">(current)</span></a></li>
                <li class="{% ifequal request.path harttvview_all_shows %}active{% endifequal %}"><a href="{% url 'harttv:view_all_shows' %}">Shows</a></li> <!--Link to Page that renders all shows currently in db, same as search_result format.-->
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Community <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'dashboard:index' %}">User Dashboard</a></li>
                    <li><a href="{% url 'harttv:top_rated_shows' %}">Top 10 Shows</a></li>
                </ul>
                <!--<li class="{% ifequal request.path harttvabout %}active{% endifequal %}"><a href="{% url 'harttv:about' %}">About</a></li>-->
                </li> 
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                <a href="#" id="nav-user" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.session.first_name}}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'dashboard:show_user' request.session.id %}">View Profile</a></li>
                    <li><a href="{% url 'dashboard:edit_user' request.session.id %}">Account Management</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right" action="{% url 'harttv:search_results' %}">
                <div class="form-group">
                <input type="text" class="form-control" placeholder="Search for a show..." name="show_search" id="show_search">
                </div>
                <button type="submit" class="btn btn-default" id="search_button">Search!</button>
            </form>
            </div><!-- /.navbar-collapse -->

            <!-- Collect the nav links, forms, and other content for toggling -->
        </div>
        </nav>
        <!--new header ends here -->
        <div class='container' style="margin-top: 100px; margin-bottom: 80px;">
        {% block content %}

        {% endblock %}
        </div>


        <footer>
        
        <div class="container-fluid footer-container">
                <a class="footer-brand" href="#">Hart<span class='hart_tv_TV'>TV</span></a>

                <p class="footer-text">2017 Michael Hartley</p>
                <p class="footer-text footer-right">mtjhartley@gmail.com</p>
                <a class="footer-text footer-right" href="https://www.github.com/mtjhartley">GitHub</a>
                <p class="footer-text footer-right">Portfolio (Coming Soon)</p>
                <p class="footer-text footer-right"></p>
                    



        </div>
        </footer>

        

    </body>
</html>

apps/harttv_app/templates/harttv_app/search.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    </head>
    <body>
        <h1>Test search page</h1>
        <form action="{% url 'harttv:search_results' %}">
            <label for='show_search'>
            <input type="text" class="form-control" placeholder="Search for a show" name="show_search">
            <button class="btn btn-default" type="submit">Search!</button>
        </form>
            
            
    
    </body>
</html>

apps/harttv_app/templates/harttv_app/search_results.html
{% extends 'harttv_app/base.html' %}
    {% block content %}
        {% if results %}
        <h2>Search results for "{{search}}"</h2>
        {% else %}
        <h2>No results found for "{{search}}". Please refine your query and try again.</h2>
        {% endif %}
        {% for show in contextShow %}
        <div class='row show-row'>
            <div class='col-md-12 show-table-header'>
                <div class='row'>
                    <div class='col-md-2'>
                        <p class='show-table-title'><a href="{% url 'harttv:view_show' show_maze_id=show.maze_id %}">{{show.name}}</a></h3>
                    </div>
                    <div class='col-md-10'>
                        <div class='stats-holder'><p class='show-table-stats'> Network: {% if not show.network %} N/A {% else %} {{show.network}} {% endif %}</p></div>
                        <div class='stats-holder'><p class='show-table-stats'>Premiered: {{show.airdate|date:"Y"}}</p></div>
                        <div class='stats-holder'><p class='show-table-stats'>ID #{{show.maze_id}}</p></div>
                    </div>
                </div>
                <div class='row'>
                    <div class='col-md-2'>
                        <a href="{% url 'harttv:view_show' show_maze_id=show.maze_id %}"><img class='all-show-image' src="{{show.image}}"></a>
                    </div>
                    <div class='col-md-10'>
                        <p class='show-table-description'>{{show.description|truncatewords:200}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endblock %}



        

apps/harttv_app/templates/harttv_app/view_episode.html
{% extends 'harttv_app/base.html' %}
    {% block content %}
        <div class='col-md-7'>
            <div class='row'>
                <p class='one-show-header' id='one-show-title'>{{show.title}}</p>
                {% if not favorited %}
                <form id='add-remove-favorite' class='one-show-header'action="{% url 'harttv:handle_add_favorite' show.id%}" method='post'>
                    {% csrf_token %}
                    <button type='submit' class='btn btn-default one-show-button'>&#9734; Add to Favorites</button>
                </form>
                {% else %}
                <form id='add-remove-favorite' class='one-show-header' action="{% url 'harttv:handle_remove_favorite' show.id%}" method='post'>
                    {% csrf_token %}
                    <button type='submit' class='btn btn-default one-show-button'>Remove From Favorites</button>
                </form>
                {% endif %}
            </div>
            <div class='row'>
                <div class='col-md-4'> <!-- this is for the show image-->
                    <img src="{{show.image_link}}" class='one-show-image'>
                </div>
                <div class='col-md-8'> <!-- this is for the show stats-->
                    <table class='table show-table'>
                        <thead>
                        </thead>
                        <tbody>
                            <tr class='show-table-row'>
                                <th class='first-column'>Episodes</th>
                                <th class='second-column'>{{num_episodes}}</th>
                            </tr>
                            <tr>
                                <th class='first-column'>Status</th>
                                <th class='second-column'>{{show.status}}</th>
                            </tr>
                            <tr>
                                <th class='first-column'>Preimere Date</th>
                                <th class='second-column'>{{show.premiered}}</th>
                            </tr>
                            <tr>
                                <th class='first-column'>Network</th>
                                <th class='second-column'>{{show.network}}</th>
                            </tr>
                            
                            <tr>
                                <th class='first-column'>Average Score</th>
                                <th class='second-column'>{{show_average_rating}} ({{show_num_users_rated}} users)</th>
                            </tr>
                            <tr>
                                <th class='first-column'>Your Score</th>
                                <th class='second-column'>{{current_rating}}</th>
                            </tr>
                            <tr>
                                <th class='first-column'>Favorites</th>
                                <th class='second-column'>{{favorites}}</th>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class='row'>
                <h3 class='episodes-header'>Comments</h3>
            </div>
            <div class='row'>
                <div class="episode_comment" >
                    <div class="row">
                        <div class='comments-container'>
                            {% for comment in comments %}
                                <div class='comment-container'>
                                    <div class="col-sm-3">
                                        <p><span class='reviewer-name'>{{comment.user.first_name}}</span></p>
                                        <p><span class='commenter-date'>{{comment.created_at|date:"m/d/y"}}</span></p>
                                    </div>
                                    <div class='col-sm-9'>
                                        <p>{{comment.comment}}</p>
                                    </div>
                                
                                    {% if comment.user.id == request.session.id %}
                                    <form action="{% url 'harttv:handle_delete_episode_comment' episode.id comment.id%}" method='post'>
                                        {% csrf_token %}
                                        <button class='btn btn-link' type='submit'>Delete Comment</button>
                                    </form>
                                </div>
                                    {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                        {% if messages %}
                        <ul>
                            <li>ATTENTION REQUIRED!</li>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <form action="{% url 'harttv:handle_add_episode_comment' episode.id%}" method='post'>
                            {% csrf_token %}
                            <textarea name='comment' id='comment' class='form-control' placeholder='What are your thoughts...?'></textarea>
                            <button type='submit' class='btn btn-default'>Add a Comment!</button>
                        </form>
                </div>

            </div><!-- md-7 ends here -->
        </div><!-- container ends here -->

        <div class='col-md-5'>
            <p id='one-show-description-header'>Episode Name: {{episode.title}} (S{{episode.season_number}}E{{episode.episode_number}})</p>
            <img src="{{episode.image_link}}" alt='episode_thumbnail' class='episode-thumbnail'>
            <p id='one-episode-description-text'>Synopsis: {{episode.summary}}</p>
            <div>
                <table class='table'>
                    <thead>
                    </thead>
                    <tbody>
                        <tr class='show-table-row'>
                            <th class='first-column'>Airdate</th>
                            <th class='second-column'>{{episode.airdate}}</th>
                        </tr>
                        <tr>
                            <th class='first-column'>Runtime</th>
                            <th class='second-column'>{{episode.runtime}}</th>
                        </tr>
                        <tr>
                            <th class='first-column'>Average Rating</th>
                            <th class='second-column'>{{episode_average_rating}} ({{episode_num_users_rated}} users)</th>
                        </tr>
                        <tr>
                            <th class='first-column'>Your Rating</th>
                            <th class='second-column'>{{episode_rating}}</th>
                        </tr>
                    
                    </tbody>
                </table>
            </div>
                <form action="{% url 'harttv:handle_update_episode_rating' episode.id %}" method='post'>
                    {% csrf_token %}
                    <div class='form-group'>
                        <label for="rating" class='add-review-title'>Rating:</label>
                        <select name='rating'>
                            {% if current_rating %}
                                {% for option in options %}
                                    <option value="{{option.0}}" {% if episode_rating == option.0 %} selected {% endif %}>{{option.1}}</option>
                                {% endfor %}
                            {% else %}
                                    <option selected disabled>Select</option>
                                {% for option in options %}
                                    <option value="{{option.0}}" {% if episode_rating == option.0 %} selected {% endif %}>{{option.1}}</option>
                                {% endfor %}
                            {% endif %}             
                        </select>
                        <button class='btn btn-default one-show-button' id='review-button'type='submit'>Submit Rating</button>
                        <!-- would be a great time to use ajax!!!-->
                    </div>
                </form>
            </div>
        </div>
    {% endblock %}